version: '3'

services:
  backend:
    build: backend
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
  # frontend:
  #   build: frontend
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - backend
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
