version: '3'

services:
  backend:
    build: backend
    environment:
      - MONGO_HOST=10.0.0.15
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - ALLOWED_ORIGINS=https://esgps.pycrs.cz
  frontend:
    build: frontend
    depends_on:
      - backend
  nginx:
    build: nginx
    depends_on:
      - backend
      - frontend
    networks:
      default:
      proxy_net:
    environment:
      - DOMAIN=esgps.pycrs.cz
      - BACKEND_ADDRESS=backend:8080
      - FRONTEND_ADDRESS=frontend:80

  # mongodb:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb_data:/data/db
volumes:
  mongodb_data:

networks:
  proxy_net:
    external: true

