spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  data:
    mongodb:
      database: es-gps
      host: localhost
      authentication-database: admin
      username: admin
      password: admin
logging:
  level:
    org.springframework.security: TRACE
    cz.pycrs: TRACE

server:
  servlet:
    session:
      timeout: 0

