spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  data:
    mongodb:
      database: es-gps
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: admin
      password: admin
      authentication-database: admin

logging:
  level:
    org.springframework.security: TRACE
    cz.pycrs: TRACE

server:
  servlet:
    session:
      timeout: 0

